### ISSUE TITLE
Reversed shooting

### ISSUE THREAD

**Issue by stephenDiosDev** [jfdoming/Project-B#2]
When you look left and shoot, the bullet will fire in the opposite direction and the bullet sprite is also facing the wrong direction when you look left

**Comment by Robertboy18** [comment]
Corrected The issue that is:  the bullet sprite now shoots in the same direction as the direction as when you look. 
![issue](https://user-images.githubusercontent.com/32393571/80854941-6ec8ea80-8bf9-11ea-816a-d636d7e888ec.PNG)
