### ISSUE TITLE
Stroheim bullet direction

### ISSUE THREAD

**Issue by AmandaOlearczuk** [jfdoming/Project-B#5]
![Untitled](https://user-images.githubusercontent.com/35851317/81327882-35f59f00-9059-11ea-8d61-4eb8db7d9e1c.png)

When stroheim is facing right, the bullets have correct direction. However when stroheim is facing left, bullets act as if the character was still facing right.

**Comment by Robertboy18** [comment]
Okay I have fixed the issue and updated the code you can check the Pull request.
